apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vikode-cert
  namespace: sock-shop
spec:
  secretName: vikode-secret
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: www.vikode.me
  dnsNames:
  - www.vikode.me