---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
# namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory  
    email: victorojetokun24@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod     
    solvers:
      - selector: {}
        http01:
          ingress:
            class: nginx